/**
 * Seed script — creates fake (completely fabricated) interviews so the
 * dashboard is never empty during development & demos.
 *
 *   npm run prisma:seed
 *
 * Requires DATABASE_URL (local Postgres or Render).
 */
import { PrismaClient } from "@prisma/client";
import { normalizeAnswers } from "../lib/answers";
import type { AnswerMap } from "../lib/validate";

const prisma = new PrismaClient();

type SeedStore = {
  name: string;
  activity_type: string;
  years_active: string;
  product_count: string;
  car_brands: string[];
};

type SeedInterview = {
  store: SeedStore;
  q: Record<string, string | string[]>;
  verdict: "POSITIVE" | "MIXED" | "NEGATIVE" | null;
  summary: string;
  note?: string;
};

const Q = (q: Record<string, string | string[]>): Record<string, string | string[]> => q;

const FAKE: SeedInterview[] = [
  {
    store: { name: "قطعات بوتیمار", activity_type: "original", years_active: "7-15", product_count: "1200", car_brands: ["irankhodro", "saipa"] },
    q: Q({
      how_clients_find: ["walk_in", "phone"],
      call_before_visit_percent: "60",
      out_of_stock_often: "weekly",
      when_out_of_stock: ["source_peer", "order"],
      biggest_problem: "پیدا کردن قطعه نایاب در بازار بزرگ تهران زمان‌بر است و مشتری را از دست می‌دهیم",
      find_part_time: "hour",
      wrong_part_mistakes: "sometimes",
      has_online_sales: "yes",
      online_method: ["instagram", "messenger"],
      online_experience: "good",
      site_benefit: ["customers", "reach", "inventory_info"],
      usage_barriers: ["complexity", "cost"],
      willing_register_products: "yes",
      register_time: "half_day",
      who_enters_products: "platform",
      delivery_preference: "garage",
      reservation_useful: "yes",
      no_show_problem: "somewhat",
      prepay_ok: "depends",
      required_info_before_buy: ["photo", "price", "stock", "brand", "compatibility"],
      willing_pay_platform: "yes",
      revenue_model: ["commission"],
      suggested_commission: "8",
      commission_pay_time: "end_month",
      free_register_plus_commission_ok: "yes",
      trust_factors: ["record", "settlement", "support"],
      show_store_info_problem: "no",
      chat_needed: "yes",
      essential_features: ["live_stock", "advanced_search", "reservation"],
      one_problem_to_solve: "جستجوی سریع قطعه با شماره فنی و اطلاع از موجودی کل بازار",
      ideal_site_role: "سایت باید مثل یک پل میان فروشندگان و تعمیرگاه‌ها عمل کند و موجودی لحظه‌ای نشان دهد",
      usage_avoid_reasons: ["low_orders"],
      seen_similar: "heard",
      will_register: "yes",
      will_register_reason: "چون مشتری امروز اول گوگل و اینستاگرام را می‌بیند؛ اگر جایگاه خوبی داشته باشیم فروش بیشتر می‌شود",
    }),
    verdict: "POSITIVE",
    summary: "فروشنده فعال و علاقه‌مند؛ آماده تست نسخه اولیه است.",
    note: "پیشنهاد داد پایلوت محدود با ۲۰ قطعه پرتیراژ انجام شود.",
  },
  {
    store: { name: "یدک‌سرا", activity_type: "aftermarket", years_active: "3-7", product_count: "450", car_brands: ["saipa"] },
    q: Q({
      how_clients_find: ["phone", "messenger", "garage_ref"],
      call_before_visit_percent: "80",
      out_of_stock_often: "daily",
      when_out_of_stock: ["source_peer", "lose_customer"],
      biggest_problem: "بیشتر مشتری‌های پراید و تیبا زنگ می‌زنند ولی سفارش حضوری نمی‌آیند؛ باید با تعمیرگاه‌ها کار کنیم",
      find_part_time: "half_day",
      wrong_part_mistakes: "often",
      has_online_sales: "never",
      online_never_reason: "زبان فنی بلد نیستیم؛ همه کار بازار بر اساس تلفن و آشناست",
      site_benefit: ["customers", "reach"],
      usage_barriers: ["trust", "tech_fear"],
      willing_register_products: "with_help",
      register_time: "day",
      who_enters_products: "paid_service",
      delivery_preference: "courier",
      reservation_useful: "unsure",
      no_show_problem: "loss",
      prepay_ok: "yes",
      required_info_before_buy: ["price", "stock", "warranty"],
      willing_pay_platform: "maybe",
      revenue_model: ["commission", "subscription"],
      suggested_commission: "5",
      commission_pay_time: "per_sale",
      free_register_plus_commission_ok: "see",
      trust_factors: ["support", "transparency"],
      show_store_info_problem: "conditions",
      chat_needed: "yes",
      essential_features: ["advanced_search", "online_payment"],
      one_problem_to_solve: "اعتماد مشتری به کیفیت قطعه؛ همه می‌ترسند قطعه تقلبی درست شود",
      ideal_site_role: "اول قیمت شفاف و بعد امکان رزرو با واریز؛ کسی برای قطعه ۲۰ هزار تومانی نقدی دلش نمی‌لرزد",
      usage_avoid_reasons: ["hard_use"],
      seen_similar: "no",
      will_register: "maybe",
      will_register_reason: "اگر در یک ماه اول سفارشی دریافت کنم حتماً می‌آیم؛ وگرنه ارزش ندارد وقت بگذارم",
    }),
    verdict: "MIXED",
    summary: "نیاز واقعی دارد ولی به سادگی استفاده شک دارد.",
  },
  {
    store: { name: "اتوپارت یدک", activity_type: "consumable", years_active: "1-3", product_count: "180", car_brands: ["irankhodro"] },
    q: Q({
      how_clients_find: ["walk_in", "referral"],
      call_before_visit_percent: "30",
      out_of_stock_often: "monthly",
      when_out_of_stock: ["order", "ask_later"],
      biggest_problem: "رقابت شدید قیمتی در لوازم مصرفی؛ حاشیه سود ما زیر ۵ درصد است",
      find_part_time: "minutes",
      wrong_part_mistakes: "rarely",
      has_online_sales: "had",
      online_method: ["classifieds", "instagram"],
      online_experience: "weak",
      online_stopped_reason: "تماس‌های بی‌پاسخ زیاد و تحویل یک‌شخصی خسته‌کننده شد؛ صرفه نداشت",
      site_benefit: ["inventory_info", "cheap_ads"],
      usage_barriers: ["race_down", "refund_fear"],
      willing_register_products: "yes",
      register_time: "lt15",
      who_enters_products: "owner",
      delivery_preference: "in_person",
      reservation_useful: "yes",
      no_show_problem: "rare",
      prepay_ok: "no",
      required_info_before_buy: ["brand", "warranty", "compatibility"],
      willing_pay_platform: "yes",
      revenue_model: ["hybrid"],
      suggested_commission: "10",
      commission_pay_time: "end_month",
      free_register_plus_commission_ok: "yes",
      trust_factors: ["reviews", "transparency"],
      show_store_info_problem: "no",
      chat_needed: "no",
      essential_features: ["fast_registration", "support"],
      one_problem_to_solve: "ورود سریع صدها فیلتر و روغن باید زیر ۵ دقیقه طول بکشد",
      ideal_site_role: "ثبت گروهی محصولات با کد فنی و پرینت لیبل برای ما کافی است",
      usage_avoid_reasons: ["mistrust"],
      seen_similar: "yes",
      will_register: "yes",
      will_register_reason: "لوازم مصرفی روزمره بهترین گزینه برای شروع هستند چون کالای پرتکرارند",
    }),
    verdict: "POSITIVE",
    summary: "فروشنده جوان و اهل تکنولوژی؛ کاملاً آگاه.",
  },
  {
    store: { name: "یدک‌لند مرکزی", activity_type: "wholesale", years_active: "gt15", product_count: "5000", car_brands: ["irankhodro", "saipa", "european"] },
    q: Q({
      how_clients_find: ["phone", "walk_in"],
      call_before_visit_percent: "90",
      out_of_stock_often: "rarely",
      when_out_of_stock: ["source_peer", "order"],
      biggest_problem: "حسابداری و اعتباردهی به فروشندگان عمده؛ پیگیری طلب‌ها انرژی‌بر است",
      find_part_time: "minutes",
      wrong_part_mistakes: "rarely",
      has_online_sales: "yes",
      online_method: ["own_site", "marketplace"],
      online_experience: "great",
      site_benefit: ["customers", "reach", "price_transparency"],
      usage_barriers: ["none"],
      willing_register_products: "yes",
      register_time: "week",
      who_enters_products: "owner",
      delivery_preference: "post",
      reservation_useful: "yes",
      no_show_problem: "no_problem",
      prepay_ok: "yes",
      required_info_before_buy: ["price", "stock", "delivery_time"],
      willing_pay_platform: "yes",
      revenue_model: ["commission", "fixed"],
      suggested_commission: "7",
      commission_pay_time: "end_month",
      free_register_plus_commission_ok: "yes",
      trust_factors: ["record", "contract", "settlement"],
      show_store_info_problem: "no",
      chat_needed: "yes",
      essential_features: ["live_stock", "advanced_search"],
      one_problem_to_solve: "تسویه و اعتبار و تخمین تقاضای ماه قبل",
      ideal_site_role: "داشبورد فروش و گزارش موجودی برای عمده‌فروش حیاتی است",
      usage_avoid_reasons: ["competition"],
      seen_similar: "yes",
      will_register: "yes",
      will_register_reason: "بازار به سمت شفافیت می‌رود؛ حضور زودهنگام مزیت است",
    }),
    verdict: "POSITIVE",
    summary: "عمده‌فروش بزرگ؛ مدل درآمدی ترکیبی را می‌پسندد.",
    note: "اصرار به داشتن صفحه گزارش ماهانه برای فروشندگان دارد.",
  },
  {
    store: { name: "قطعه‌فروشی عباس", activity_type: "original", years_active: "gt15", product_count: "800", car_brands: ["european"] },
    q: Q({
      how_clients_find: ["walk_in", "garage_ref"],
      call_before_visit_percent: "50",
      out_of_stock_often: "weekly",
      when_out_of_stock: ["ask_later", "lose_customer"],
      biggest_problem: "قطعات وارداتی اروپایی را فقط از دو تا تأمین‌کننده می‌توانیم بخریم؛ قیمت دست آن‌هاست",
      find_part_time: "day",
      wrong_part_mistakes: "sometimes",
      has_online_sales: "never",
      online_never_reason: "مشتری ما تعمیرکار و به‌شدت سنتی است؛ به جای سایت به صفحه تلگرام ما اکتفا کرده",
      site_benefit: ["reach"],
      usage_barriers: ["trust", "complexity"],
      willing_register_products: "no",
      register_time: "week",
      who_enters_products: "platform",
      delivery_preference: "in_person",
      reservation_useful: "no",
      reservation_not_good_reason: "قطعات اروپایی نایاب‌اند؛ اگر رزرو کنم و نیایند ضرر صددرصدی دارم",
      no_show_problem: "loss",
      prepay_ok: "yes",
      required_info_before_buy: ["photo", "brand", "compatibility", "warranty"],
      willing_pay_platform: "no",
      not_willing_reason: "حاشیه سود قطعه اروپایی کم است و هر درصدی ما را بی‌سود می‌کند",
      revenue_model: ["dont_know"],
      free_register_plus_commission_ok: "see",
      trust_factors: ["contract", "record"],
      show_store_info_problem: "yes",
      chat_needed: "yes",
      essential_features: ["advanced_search", "online_payment"],
      one_problem_to_solve: "پیدا کردن قطعات نایاب وارداتی از کل ایران با استعلام اصالت",
      ideal_site_role: "سایت باید استعلام کد فنی قطعه اروپایی را یک‌جا کند؛ همین یک کار کافی است",
      usage_avoid_reasons: ["mistrust"],
      seen_similar: "no",
      will_register: "no",
      will_register_reason: "تا وقتی ثبت و مدیریت امن و ساده نباشد با مشتری تلفنی راحت‌ترم",
    }),
    verdict: "NEGATIVE",
    summary: "به پلتفرم بدبین است؛ باید با نمونه کار رضایتش را جلب کرد.",
  },
  {
    store: { name: "پارت‌شاپ آنلاین", activity_type: "online", years_active: "3-7", product_count: "3000", car_brands: ["chinese", "saipa"] },
    q: Q({
      how_clients_find: ["messenger", "phone"],
      call_before_visit_percent: "70",
      out_of_stock_often: "weekly",
      when_out_of_stock: ["order", "source_peer"],
      biggest_problem: "اعتماد مشتری به اصالت قطعه در فروش آنلاین؛ عکس و برند به‌تنهایی کافی نیست",
      find_part_time: "hour",
      wrong_part_mistakes: "sometimes",
      has_online_sales: "yes",
      online_method: ["own_site", "instagram", "marketplace"],
      online_experience: "great",
      site_benefit: ["customers", "inventory_info", "price_transparency", "cheap_ads"],
      usage_barriers: ["none"],
      willing_register_products: "yes",
      register_time: "lt15",
      who_enters_products: "owner",
      delivery_preference: "courier",
      reservation_useful: "yes",
      no_show_problem: "rare",
      prepay_ok: "yes",
      required_info_before_buy: ["photo", "price", "brand", "warranty"],
      willing_pay_platform: "yes",
      revenue_model: ["commission"],
      suggested_commission: "15",
      commission_pay_time: "per_sale",
      free_register_plus_commission_ok: "yes",
      trust_factors: ["reviews", "support", "settlement"],
      show_store_info_problem: "no",
      chat_needed: "yes",
      essential_features: ["live_stock", "advanced_search", "ratings"],
      one_problem_to_solve: "حذف واسطه و رسیدن مستقیم قطعه به تعمیرگاه مشتری",
      ideal_site_role: "شباهت به شیپور اما تخصصی؛ با گارانتی اصالت کالا",
      usage_avoid_reasons: ["no_customers"],
      seen_similar: "yes",
      will_register: "yes",
      will_register_reason: "ما تجربه فروش آنلاین را داریم و قطعاً یک بازارگاه تخصصی کمکی می‌کند",
    }),
    verdict: "POSITIVE",
    summary: "فروشنده آنلاین باتجربه؛ شریک استراتژیک احتمالی برای پایلوت.",
  },
  {
    store: { name: "یدک‌یار", activity_type: "garage_shop", years_active: "3-7", product_count: "260", car_brands: ["saipa", "irankhodro"] },
    q: Q({
      how_clients_find: ["garage_ref", "referral", "walk_in"],
      call_before_visit_percent: "20",
      out_of_stock_often: "daily",
      when_out_of_stock: ["source_peer", "lose_customer"],
      biggest_problem: "وقتی قطعه را نداریم مشتری همان‌لحظه می‌رود تعمیرگاه بعدی؛ سرعت مهم‌ترین چیز است",
      find_part_time: "half_day",
      wrong_part_mistakes: "sometimes",
      has_online_sales: "never",
      online_never_reason: "من تعمیرکارم نه فروشنده اینترنتی؛ بگذارید کسی دیگر پاسخگوی سایت باشد",
      site_benefit: ["customers", "inventory_info"],
      usage_barriers: ["complexity", "tech_fear"],
      willing_register_products: "with_help",
      register_time: "day",
      who_enters_products: "paid_service",
      delivery_preference: "garage",
      reservation_useful: "yes",
      no_show_problem: "rare",
      prepay_ok: "depends",
      required_info_before_buy: ["stock", "delivery_time", "compatibility"],
      willing_pay_platform: "maybe",
      revenue_model: ["commission", "hybrid"],
      suggested_commission: "5",
      commission_pay_time: "per_sale",
      free_register_plus_commission_ok: "yes",
      trust_factors: ["support", "record"],
      show_store_info_problem: "no",
      chat_needed: "yes",
      essential_features: ["reservation", "support"],
      one_problem_to_solve: "دسترسی فوری به قطعه بدون اینکه ماشین مشتری مدت‌ها در گاراژ بماند",
      ideal_site_role: "یک دکمه «نیاز دارم» که به همه فروشندگان شهر برای تأمین فوری بگوید",
      usage_avoid_reasons: ["hard_use"],
      seen_similar: "heard",
      will_register: "maybe",
      will_register_reason: "اگر ثبت ساده باشد کمک می‌کند؛ وقت گاراژ ندارم",
    }),
    verdict: "MIXED",
    summary: "نیاز فوری به موجودی لحظه‌ای دارد؛ قانع‌شدنش به سادگی بستگی دارد.",
  },
  {
    store: { name: "تفکیک یدک", activity_type: "aftermarket", years_active: "lt1", product_count: "90", car_brands: ["irankhodro"] },
    q: Q({
      how_clients_find: ["messenger", "referral"],
      call_before_visit_percent: "85",
      out_of_stock_often: "daily",
      when_out_of_stock: ["lose_customer", "ask_later"],
      biggest_problem: "تازه‌کارم؛ هنوز نمی‌دانم کدام قطعه‌ها پرتیراژند و کدام را نباید انبار کنم",
      find_part_time: "hour",
      wrong_part_mistakes: "sometimes",
      has_online_sales: "had",
      online_method: ["instagram", "classifieds"],
      online_experience: "average",
      online_stopped_reason: "وقت برای پست‌گذاشتن عکس نداشتم؛ سفارش‌ها هم کم بود",
      site_benefit: ["customers", "cheap_ads", "inventory_info"],
      usage_barriers: ["cost"],
      willing_register_products: "yes",
      register_time: "half_day",
      who_enters_products: "owner",
      delivery_preference: "post",
      reservation_useful: "yes",
      no_show_problem: "somewhat",
      prepay_ok: "yes",
      required_info_before_buy: ["price", "stock", "photo"],
      willing_pay_platform: "yes",
      revenue_model: ["subscription"],
      suggested_commission: "3",
      commission_pay_time: "periodic",
      free_register_plus_commission_ok: "yes",
      trust_factors: ["support", "transparency"],
      show_store_info_problem: "conditions",
      chat_needed: "yes",
      essential_features: ["fast_registration", "advanced_search"],
      one_problem_to_solve: "دانستن اینکه کدام قطعات را بخرم تا کالای خواب در انبار نماند",
      ideal_site_role: "هوش تجاری ساده برای فروشنده تازه‌کار: آمار فروش و تقاضا",
      usage_avoid_reasons: ["low_orders", "no_customers"],
      seen_similar: "heard",
      will_register: "maybe",
      will_register_reason: "امیدوارم شروع کسب‌وکار را راحت‌تر کند؛ شرط می‌گذارد ببیند مشتری می‌آید یا نه",
    }),
    verdict: "MIXED",
    summary: "مشتاق ولی به نتیجه بلندمدت بدبین.",
  },
  {
    store: { name: "یدک‌پژو", activity_type: "original", years_active: "7-15", product_count: "1500", car_brands: ["irankhodro"] },
    q: Q({
      how_clients_find: ["walk_in", "phone"],
      call_before_visit_percent: "65",
      out_of_stock_often: "monthly",
      when_out_of_stock: ["order", "ask_later"],
      biggest_problem: "بعضی قطعات پژو از خط تولید خارج شده و دیگر نیست؛ مشتری مجبور است از ضایعاتی‌ها بخرد",
      find_part_time: "half_day",
      wrong_part_mistakes: "rarely",
      has_online_sales: "yes",
      online_method: ["instagram", "messenger"],
      online_experience: "good",
      site_benefit: ["reach", "inventory_info"],
      usage_barriers: ["race_down"],
      willing_register_products: "yes",
      register_time: "half_day",
      who_enters_products: "owner",
      delivery_preference: "in_person",
      reservation_useful: "yes",
      no_show_problem: "rare",
      prepay_ok: "depends",
      required_info_before_buy: ["compatibility", "brand", "stock"],
      willing_pay_platform: "yes",
      revenue_model: ["commission", "hybrid"],
      suggested_commission: "10",
      commission_pay_time: "end_month",
      free_register_plus_commission_ok: "yes",
      trust_factors: ["reviews", "record"],
      show_store_info_problem: "no",
      chat_needed: "yes",
      essential_features: ["advanced_search", "ratings", "online_payment"],
      one_problem_to_solve: "نشان دادن سازگاری دقیق قطعه با مدل و سال خودرو",
      ideal_site_role: "کاتالوگ تعاملی که با شماره شاسی خودرو، لیست قطعات لازم را بدهد",
      usage_avoid_reasons: ["competition"],
      seen_similar: "no",
      will_register: "yes",
      will_register_reason: "تخصص ما پژو است؛ پلتفرمی که این تخصص را نمایش دهد به ما مشتری می‌دهد",
    }),
    verdict: "POSITIVE",
    summary: "فروشنده تخصصی پژو؛ ارزش بالای داده‌ی سازگاری را می‌فهمد.",
  },
  {
    store: { name: "امیر یدک تعویضی", activity_type: "aftermarket", years_active: "1-3", product_count: "320", car_brands: ["saipa", "motorcycle"] },
    q: Q({
      how_clients_find: ["phone", "messenger", "referral"],
      call_before_visit_percent: "75",
      out_of_stock_often: "daily",
      when_out_of_stock: ["source_peer"],
      biggest_problem: "موتورسیکلت و پراید هر روز پرس‌وجوی مشترک دارد ولی قیمت تأمین ما بالاست",
      find_part_time: "hour",
      wrong_part_mistakes: "often",
      has_online_sales: "never",
      online_never_reason: "کارت و عکس قطعه‌ها را ندارم؛ تلگرام کافی است",
      site_benefit: ["customers", "inventory_info"],
      usage_barriers: ["complexity", "trust", "cost"],
      willing_register_products: "with_help",
      register_time: "day",
      who_enters_products: "paid_service",
      delivery_preference: "depends",
      reservation_useful: "no",
      reservation_not_good_reason: "مشتری همین‌حالا می‌آید یا نمی‌آید؛ مفهوم رزرو برای بازار ما بی‌معناست",
      no_show_problem: "loss",
      prepay_ok: "no",
      required_info_before_buy: ["price", "stock"],
      willing_pay_platform: "no",
      not_willing_reason: "هزینه‌های ما زیاد است؛ هر مبلغی سنگین است",
      revenue_model: ["dont_know"],
      free_register_plus_commission_ok: "no",
      trust_factors: ["support"],
      show_store_info_problem: "yes",
      chat_needed: "unsure",
      essential_features: ["stock", "support"],
      one_problem_to_solve: "کاهش هزینه تأمین با اتحاد فروشندگان محله",
      ideal_site_role: "سایت نمی‌خواهم؛ فقط اگر قیمت تأمین پایین‌تر بیاید جذاب است",
      usage_avoid_reasons: ["high_cost", "no_customers"],
      seen_similar: "no",
      will_register: "no",
      will_register_reason: "عملاً نمی‌بینم چه چیزی برای یک مغازه کوچک اضافه دارد",
    }),
    verdict: "NEGATIVE",
    summary: "سؤال اصلی مدل درآمدی: برای مغازه کوچک چه ارزشی می‌سازیم؟",
  },
  {
    store: { name: "قطعات غرب", activity_type: "wholesale", years_active: "7-15", product_count: "2400", car_brands: ["irankhodro", "saipa", "chinese"] },
    q: Q({
      how_clients_find: ["phone", "walk_in", "messenger"],
      call_before_visit_percent: "85",
      out_of_stock_often: "weekly",
      when_out_of_stock: ["source_peer", "order"],
      biggest_problem: "تعیین موجودی برای فروش عمده بدون سیستم؛ همه چیز توی دفتر و ذهن است",
      find_part_time: "half_day",
      wrong_part_mistakes: "sometimes",
      has_online_sales: "yes",
      online_method: ["messenger", "marketplace"],
      online_experience: "good",
      site_benefit: ["reach", "inventory_info", "price_transparency"],
      usage_barriers: ["none"],
      willing_register_products: "yes",
      register_time: "day",
      who_enters_products: "owner",
      delivery_preference: "post",
      reservation_useful: "yes",
      no_show_problem: "somewhat",
      prepay_ok: "yes",
      required_info_before_buy: ["price", "stock", "brand"],
      willing_pay_platform: "maybe",
      revenue_model: ["subscription"],
      suggested_commission: "6",
      commission_pay_time: "periodic",
      free_register_plus_commission_ok: "see",
      trust_factors: ["settlement", "transparency", "support"],
      show_store_info_problem: "conditions",
      chat_needed: "yes",
      essential_features: ["live_stock", "advanced_search"],
      one_problem_to_solve: "انبار دارم ولی هیچ‌کس جز نزدیکان نمی‌داند چه دارم؛ می‌خواهم موجودی دیده شود",
      ideal_site_role: "ویترین اتوماتیک انبار من با قیمت قابل‌مذاکره برای عمده‌فروشان",
      usage_avoid_reasons: ["competition"],
      seen_similar: "heard",
      will_register: "maybe",
      will_register_reason: "اگر نسخه عمده‌فروشی (قیمت بست‌بندی) داشته باشد حتماً؛ وگرنه تعرفه خرده‌فروشی به کارم نمی‌آید",
    }),
    verdict: "MIXED",
    summary: "مشتری بالقوه نسخه عمده‌فروشی؛ نیاز به مدل قیمت‌گذاری خاص.",
  },
  {
    store: { name: "یدک‌بازار هوشمند", activity_type: "online", years_active: "1-3", product_count: "1100", car_brands: ["european", "asian"] },
    q: Q({
      how_clients_find: ["messenger", "phone", "website"],
      call_before_visit_percent: "50",
      out_of_stock_often: "monthly",
      when_out_of_stock: ["order", "source_peer"],
      biggest_problem: "تشخیص اصالت قطعات وارداتی؛ مشتری عکس اتاق چینی را با برند اصلی اشتباه می‌گیرد",
      find_part_time: "hour",
      wrong_part_mistakes: "rarely",
      has_online_sales: "yes",
      online_method: ["own_site", "marketplace", "instagram"],
      online_experience: "great",
      site_benefit: ["customers", "reach", "price_transparency"],
      usage_barriers: ["none"],
      willing_register_products: "yes",
      register_time: "lt15",
      who_enters_products: "owner",
      delivery_preference: "courier",
      reservation_useful: "yes",
      no_show_problem: "rare",
      prepay_ok: "yes",
      required_info_before_buy: ["photo", "brand", "compatibility", "warranty"],
      willing_pay_platform: "yes",
      revenue_model: ["commission"],
      suggested_commission: "12",
      commission_pay_time: "per_sale",
      free_register_plus_commission_ok: "yes",
      trust_factors: ["reviews", "settlement", "support"],
      show_store_info_problem: "no",
      chat_needed: "yes",
      essential_features: ["live_stock", "advanced_search", "online_payment", "ratings"],
      one_problem_to_solve: "درگاه پرداخت امن بین‌المللی برای فروش قطعات وارداتی به سراسر ایران",
      ideal_site_role: "پلتفرم تخصصی با تخمین اصالت، گارانتی و حمل سریع",
      usage_avoid_reasons: ["no_customers"],
      seen_similar: "yes",
      will_register: "yes",
      will_register_reason: "همه زیرساخت فروش آنلاین را داریم؛ فقط به ترافیک تخصصی نیاز داریم",
    }),
    verdict: "POSITIVE",
    summary: "یکی از کاندیدهای اصلی پایلوت؛ تیم پشتیبانی دارد.",
    note: "پیشنهاد شد متن قرارداد همکاری شفاف باشد.",
  },
];

async function main() {
  const existing = await prisma.interview.count();
  if (existing > 0) {
    console.log(
      `SKIP: database already has ${existing} interviews. ` +
        "Nothing was changed (run against an empty DB to reseed).",
    );
    return;
  }

  console.log("Clearing existing data...");
  await prisma.interviewAnswer.deleteMany();
  await prisma.interviewNote.deleteMany();
  await prisma.store.deleteMany();
  await prisma.interview.deleteMany();

  console.log(`Seeding ${FAKE.length} fake interviews...`);
  for (let i = 0; i < FAKE.length; i++) {
    const fake = FAKE[i];
    const answerMap = fake.q as unknown as AnswerMap;
    const answers = normalizeAnswers(answerMap);
    const interview = await prisma.interview.create({
      data: {
        code: i + 1,
        status: "COMPLETED",
        verdict: fake.verdict,
        summary: fake.summary,
        completedAt: new Date(),
        store: {
          create: {
            name: fake.store.name,
            activityType: fake.store.activity_type,
            yearsActive: fake.store.years_active,
            productCount: Number(fake.store.product_count) || null,
            carBrands: JSON.stringify(fake.store.car_brands),
          },
        },
        answers: {
          create: answers.map((a) => ({
            questionKey: a.questionKey,
            answer: a.answer,
            answerData: a.answerData,
            questionLabel: a.questionLabel,
            questionGroup: a.questionGroup,
          })),
        },
      },
    });
    if (fake.note) {
      await prisma.interviewNote.create({
        data: { interviewId: interview.id, content: fake.note },
      });
    }
  }

  const count = await prisma.interview.count();
  console.log(`Done. ${count} interviews seeded.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());